title: Internet Connectivity & Development Outcomes

description: Policy Evidence from Global Broadband Expansion

url: "https://sara-murley.github.io"
baseurl: "/MDF-final-project"

remote_theme: just-the-docs/just-the-docs

color_scheme: custom

search_enabled: true
heading_anchors: true

nav_enabled: true
nav_sort: case_sensitive

aux_links:
  GitHub Repository:
    - "https://github.com/sara-murley/MDF-final-project"

footer_content: "PPOL 5206 Big Data Analytics Project · Georgetown University"

plugins:
  - jekyll-feed